In [182]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [183]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [184]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [185]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [186]:
lc = LabelEncoder()
df['Gender'] = lc.fit_transform(df['Gender'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [187]:
df['Gender'].value_counts()

Gender
1    5457
0    4543
Name: count, dtype: int64

In [188]:
ohe = OneHotEncoder(sparse_output=False)
geography = ohe.fit_transform(df[['Geography']])  # you can also use df['Geography'].toarray().reshape(-1, 1) instead of sparse_output=False
geography

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [189]:
feature_names = ohe.get_feature_names_out(['Geography'])
feature_names

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [190]:
df2 = pd.DataFrame(geography, columns=feature_names)
df2.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [191]:
data = pd.concat([df, df2], axis=1)
data.drop('Geography', axis=1, inplace=True)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [192]:
with open ('label_encoder.pkl', 'wb') as f:
    pickle.dump(lc, f)   

with open ('onehot_encoder.pkl', 'wb') as f:
    pickle.dump(ohe, f)

In [193]:
x = data.drop('Exited', axis=1)
y = data['Exited']

In [194]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [195]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [196]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [197]:
import tensorflow as tf

In [198]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [199]:
(X_train.shape[1],)

(12,)

In [200]:
model = Sequential(
    [
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid'),
    ]
)

In [201]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [202]:
from tensorflow.keras.optimizers import Adam
opt = Adam(learning_rate=0.001)
from tensorflow.keras.losses import BinaryCrossentropy
loss = BinaryCrossentropy()

In [203]:
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

In [204]:
log_dir = 'logs/fit'

In [205]:
tensor_flow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
early_topping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [206]:
history = model.fit(X_train, y_train,validation_data=(X_test,y_test), epochs=100, callbacks=[tensor_flow_callback,early_topping_callback])

Epoch 1/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8007 - loss: 0.4568 - val_accuracy: 0.8273 - val_loss: 0.4000
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8314 - loss: 0.3978 - val_accuracy: 0.8563 - val_loss: 0.3649
Epoch 3/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8507 - loss: 0.3639 - val_accuracy: 0.8630 - val_loss: 0.3464
Epoch 4/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8524 - loss: 0.3501 - val_accuracy: 0.8620 - val_loss: 0.3415
Epoch 5/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8564 - loss: 0.3441 - val_accuracy: 0.8627 - val_loss: 0.3455
Epoch 6/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8580 - loss: 0.3409 - val_accuracy: 0.8680 - val_loss: 0.3389
Epoch 7/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8571 - loss: 0.3375 - val_accuracy: 0.8620 - val_loss: 0.3383
Epoch 8/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8583 - loss: 0.3329 - val_accuracy: 0.8660 - val_loss: 0.3377
Epoch 9/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3305 - val_accuracy: 0.8587 - val_loss: 0.3415
Epoch 10/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8610 - loss: 0.3292 - val_accuracy: 0.8653 - val_loss: 0.3390
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8609 - loss: 0.3262 - val_accuracy: 0.8660 - val_loss: 0.3347
Epoch 12/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3230 - val_accuracy: 0.8673 - val_loss: 0.3355
Epoch 13/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8639 - loss: 0.3222 - val_accuracy: 0.8627 - val_loss: 0.3429
Epoch 14/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8649 - loss: 0.3190 - val_accuracy: 0.8667 - val_loss: 0.3398
Epoch 15/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3192 - val_accuracy: 0.8683 - val_loss: 0.3330
Epoch 16/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8681 - loss: 0.3149 - val_accuracy: 0.8707 - val_loss: 0.3362
Epoch 17/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8673 - loss: 0.3158 - val_accuracy: 0.8657 - val_loss: 0.3381
Epoch 18/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8669 - loss: 0.3131 - val_accuracy: 0.8687 - val_loss: 0.3323
Epoch 19/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8681 - loss: 0.3104 - val_accuracy: 0.8673 - val_loss: 0.3325
Epoch 20/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8681 - loss: 0.3095 - val_accuracy: 0.8647 - val_loss: 0.3368
Epoch 21/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3080 - val_accuracy: 0.8667 - val_loss: 0.3383
Epoch 22/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3064 - val_accuracy: 0.8653 - val_loss: 0.3383
Epoch 23/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8731 - loss: 0.3048 - val_accuracy: 0.8620 - val_loss: 0.3380
Epoch 24/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8697 - loss: 0.3037 - val_accuracy: 0.8680 - val_loss: 0.3321
Epoch 25/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8731 - loss: 0.3003 - val_accuracy: 0.8673 - val_loss: 0.3407
Epoch 26/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8737 - loss: 0.3007 - val_accuracy: 0.8667 - val_loss: 0.3343
Epoch 27/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8737 - loss: 0.2987 - val_accuracy: 0.8697 - val_loss: 0.3342
Epoch 28/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8744 - loss: 0.2979 - val_accuracy: 0.8667 - val_loss: 0.3372
Epoch 29/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8750 - loss: 0.2959 - val_accuracy: 0.8607 - val_loss: 0.3427
Epoch 30/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8769 - loss: 0.2949 - val_accuracy: 0.8657 - val_loss: 0.3342
Epoch 31/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8754 - loss: 0.2933 - val_accuracy: 0.8687 - val_loss: 0.3385
Epoch 32/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8756 - loss: 0.2923 - val_accuracy: 0.8617 - val_loss: 0.3404
Epoch 33/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8761 - loss: 0.2916 - val_accuracy: 0.8700 - val_loss: 0.3394
Epoch 34/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8767 - loss: 0.2898 - val_accuracy: 0.8607 - val_loss: 0.3419

In [207]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [208]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [209]:
# %tensorboard --logdir logs/fit